# pull official base image
FROM python:3.9.2

# set environment varibles
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV HOME /home/app

# set work directory
WORKDIR $HOME

# install psycopg2 dependencies
RUN apt-get update && apt-get install -y  \
    apt-utils \
    cron \
    curl \
    wget \
    git \
    unzip \
    gcc  \
    musl-dev

# install dependencies
RUN pip install --upgrade pip
RUN pip install -U pipenv
COPY /app/Pipfile $HOME/Pipfile
COPY /app/Pipfile.lock $HOME/Pipfile.lock
COPY /docker/docker_entrypoint_local.sh /docker_entrypoint.sh
RUN pipenv install --python 3.9 --deploy --system

# copy project
COPY /app $HOME

EXPOSE 8000

RUN chmod +x /docker_entrypoint.sh
ENTRYPOINT ["/docker_entrypoint.sh"]