FROM nginx:1.22.0-alpine
RUN apk --no-cache add shadow && usermod -u 1000 nginx && groupmod -g 1000 nginx
COPY /docker/config/etc/nginx/nginx.conf /etc/nginx/nginx.conf
COPY /docker/config/etc/nginx/conf.d/default.dev.conf /etc/nginx/conf.d/default.conf
COPY /docker/config/etc/nginx/conf.d/timeout.conf /etc/nginx/conf.d/timeout.conf
